import './style.css';
import './archive.css';
import './civilization.css';
import {landmarks} from './civilization';
import {readSave,zones,worldAt,dayNumber,mergeEvents,importData,validateEvent,type ZoneId,type LifeEvent} from './state';
import {createWorld} from './world';
import {assignIdea,pauseSwarm,watchSwarm,type SwarmState} from './swarm';
import {projectsAt,projectContext,type LivingProject} from './projects';
import {inventionEvents,inventionProjects} from './inventory';
import {progression,truthOf,workTypes,type WorkType} from './progression';
import {assetName} from './architecture';
import {projectVisualFeatures} from './project-assets';
import {connectRepository,type SyncStatus} from './repository';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`
 <main class="shell">
 <div id="world" class="world"></div>
 <aside class="archive-rail"><a class="brand" href="./" aria-label="Karmic Life home"><span>KARMIC<br>LIFE GAME<small>YOUR LIVING ARCHIVE</small></span></a><nav aria-label="Archive navigation"><button class="rail-active" id="nav-world">⌂ <span>My world</span></button><button id="nav-archive">▧ <span>Archive</span></button><button id="nav-calendar">▦ <span>Calendar</span></button><button id="nav-agents">◉ <span>Agents</span></button><button id="nav-ideas">✦ <span>Ideas</span></button><button id="nav-about">ⓘ <span>About</span></button></nav><div class="rail-story"><span>✧</span><p>Same player.<br>Bigger map.<br><em>Brighter tomorrow.</em></p><div class="pixel-sprout">♠</div><small>Every idea has<br>a place to grow.</small></div></aside>
 <header class="topbar"><div class="archive-heading"><span class="eyebrow">THE STORY KEEPS GROWING</span><h1>KARMIC LIFE</h1><p>PERSONAL CIVILIZATION OS</p></div><div class="top-actions"><span class="save-indicator" id="save-status">● Local world</span><button id="open-import" class="button subtle">↥ Import history</button><button id="open-idea" class="button gold">＋ New idea</button></div></header>
 <div class="breadcrumb">⌂ <span>/</span> Archive <span class="breadcrumb-note">IDEAS TODAY. A BRIGHTER TOMORROW. 🌱</span></div>
 <section class="browse-panel"><h2>▦ Browse archive</h2><div class="calendar-heading"><button id="calendar-prev" aria-label="Previous month">‹</button><strong id="calendar-month"></strong><button id="calendar-next" aria-label="Next month">›</button></div><div class="calendar-week">${['M','T','W','T','F','S','S'].map(d=>`<span>${d}</span>`).join('')}</div><div id="calendar-days" class="calendar-days"></div><div class="browse-divider"></div><h3>Explore your districts</h3><div class="district-chips">${zones.map(z=>`<button data-browse-zone="${z.id}"><i style="background:${z.color}"></i>${z.name}</button>`).join('')}</div><button id="explore" class="button atlas-button">Open island atlas ↗</button><div class="local-notice"><strong>✓ Your world is saved</strong><p>Import conversations to grow the island. Contributions are saved to the shared repo; a local backup stays on this device.</p></div></section>
 <div class="stage-heading"><span class="featured-badge">✦ YOUR LIVING WORLD</span><span id="stage-date"></span></div>
 <section class="intro"><div class="eyebrow">ONE WORLD. ENDLESS POSSIBILITIES.</div><div class="world-stats"><div><strong id="district-count">12</strong><span>districts</span></div><div><strong id="project-count">77</strong><span>living ideas</span></div><div><strong id="event-count">12</strong><span>memories</span></div><div><strong id="xp-count">240</strong><span>fantasy XP</span></div></div></section>
 <aside class="activity-panel"><section class="how-card"><h2>✧ How it grows</h2><div><i>☏</i><p><strong>1. Conversations</strong><small>Your ideas, questions, plans and discoveries.</small></p></div><div><i>▧</i><p><strong>2. A living world</strong><small>Memories become places with stories to explore.</small></p></div><div><i>◉</i><p><strong>3. Idea companions</strong><small>Local agents explore, question and develop your ideas.</small></p></div></section><section class="live-card"><h2>◉ Agent activity <span id="agent-live-state">LOCAL</span></h2><div id="activity-feed"><p>Connecting to your companions…</p></div><button id="activity-open" class="button wide">Visit Agent HQ ↗</button></section><section class="archive-note"><span>✦</span><p>Ideas are seeds.<br><strong>Let your world grow.</strong></p></section></aside>
 <nav class="side-tools" aria-label="World controls"><button id="reset-camera" title="Reset camera" aria-label="Reset camera">⌂</button><button id="zoom-in" title="Zoom in" aria-label="Zoom in">＋</button><button id="zoom-out" title="Zoom out" aria-label="Zoom out">−</button><span></span><button id="toggle-night" title="Toggle day and night" aria-label="Toggle day and night">☾</button><button id="toggle-labels" title="Toggle district labels" aria-label="Toggle district labels">Aa</button></nav>
 <aside class="quest-panel"><h2>✦ Grow your civilization</h2><p>Real work leaves a mark here.</p><div id="growth-quests"></div><div class="quest-progress" id="growth-progress"></div></aside><aside class="mini-map"><header>World map <span>YOUR INVENTIONS</span></header><div id="mini-map-content"></div><button id="map-overview">Explore every neighborhood ↗</button></aside><div class="civilization-note"><strong>Ideas today. A bigger world.</strong>YOUR HISTORY BECOMES A PLACE.</div><div class="compass" aria-hidden="true"><span>N</span>✧</div>
 <aside id="district-panel" class="district-panel" hidden aria-label="District details"><button class="close" id="close-district" aria-label="Close district">×</button><div id="district-content"></div></aside>
 <div class="bottom-area"><div class="journey"><div><span class="eyebrow">DAILY WORLD SNAPSHOTS</span><h2 id="day-heading">Day 22 <span>· September 22</span></h2></div><div class="journey-controls"><button id="prev-day" aria-label="Previous snapshot">←</button><select id="date-picker" aria-label="World snapshot date"></select><button id="next-day" aria-label="Next snapshot">→</button></div><button id="archive-import" class="button subtle">Import history ↥</button><button id="open-journal" class="button subtle">Open journal ↗</button></div><div id="snapshot-strip" class="snapshot-strip"></div><div class="footer"><span>Drag to orbit <i>·</i> Scroll to zoom</span><button id="open-coverage">History partially imported ⓘ</button><button id="export-save">Export world ↗</button></div></div>
 <div id="toast" role="status" aria-live="polite" hidden></div>
 <dialog id="modal"><button id="close-modal" class="close" aria-label="Close dialog">×</button><div id="modal-content"></div></dialog>
 <input id="file-input" type="file" accept=".json,application/json" hidden>
 </main>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
for(const [id,label] of Object.entries({'nav-world':'My world','nav-archive':'Archive','nav-calendar':'Calendar','nav-agents':'Agents','nav-ideas':'Ideas','nav-about':'About'})){ $(id).setAttribute('aria-label',label);$(id).title=label;}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let save=readSave();let dates:string[]=[];let date='';let activeZone:ZoneId|undefined;let toastTimer:ReturnType<typeof setTimeout>;
let swarm:SwarmState|undefined;let swarmDialog=false;let lastSwarmSignature='';
let calendarMonth='';
let repository:ReturnType<typeof connectRepository>|undefined;let repoStatus:SyncStatus={status:'waiting',message:'Connecting to the shared world…'};
let activeProject:string|undefined;
const symbols:Record<string,string>={energy:'✣',phone:'▯',robot:'◉',media:'▶',health:'✚',science:'✧',network:'▦',temple:'♜',logistics:'⇄',materials:'▧',game:'◆',garden:'❀',workshop:'⚒'};
function projectTile(p:LivingProject){return `<button class="project-tile" data-project="${escape(p.id)}"><i style="--project-color:${zones.find(z=>z.id===p.zone)!.color}">${symbols[p.motif]}</i><span><strong>${escape(p.name)}</strong><small>${escape(zones.find(z=>z.id===p.zone)!.name)} · Plot ${p.plot+1}</small><small>Level ${progression(p.events).level} · ${progression(p.events).stage}</small></span><b>↗</b></button>`;}
function showProjects(){const projects=projectsAt(save,date);modal(`<div class="eyebrow">YOUR PERSONAL CIVILIZATION</div><h2>Ideas that live here.</h2><p>${projects.length} permanent places through ${formatDate(date)}. Search a name, a detail, or a connection.</p><div class="project-filters"><label>Search your inventions<input id="project-search" type="search" placeholder="WindPanel, magnetic iron, robotics…"></label><label>District<select id="project-zone"><option value="">All districts</option>${zones.map(z=>`<option value="${z.id}">${z.name}</option>`).join('')}</select></label></div><p id="project-results-count" role="status"></p><div id="project-results" class="project-library"></div><p class="fine-print">Each place holds an evolving idea. Add a new invention or another development to an existing project; its address stays the same.</p>`);function filter(){const q=$<HTMLInputElement>('project-search').value.trim().toLocaleLowerCase(),zone=$<HTMLSelectElement>('project-zone').value;const found=projects.filter(p=>(!zone||p.zone===zone)&&[p.name,...p.events.flatMap(e=>[e.title,e.summary,e.date])].join(' ').toLocaleLowerCase().includes(q));$('project-results-count').textContent=`${found.length} of ${projects.length} projects`;$('project-results').innerHTML=found.map(projectTile).join('')||'<p>No matching inventions at this point in the timeline.</p>';}$('project-search').oninput=filter;$('project-zone').onchange=filter;filter();}
function showProject(id:string,move=true){const p=projectsAt(save,date).find(p=>p.id===id);if(!p){closeDistrict();return;}activeProject=id;activeZone=p.zone;if(move)world?.focusProject(id);const related=projectsAt(save,date).filter(q=>p.links.includes(q.id)||q.links.includes(p.id));$('district-content').innerHTML=`<div class="eyebrow">${escape(zones.find(z=>z.id===p.zone)!.name)} · PLOT ${p.plot+1}</div><span class="district-symbol">${symbols[p.motif]}</span><h2>${escape(p.name)}</h2><p class="description">Level ${progression(p.events).level} · ${progression(p.events).stage}<br>${progression(p.events).sessions} work entries · ${p.events.length} developments</p><p class="fine-print">A permanent place in your civilization. Recorded research adds equipment; design adds a wing; prototypes, tests, and launches add flags, lab towers, and golden gateways.</p>${projectVisualFeatures(p.id).length?`<section class="building-story"><h3>What this building represents</h3><ul>${projectVisualFeatures(p.id).map(feature=>`<li>${escape(feature)}</li>`).join('')}</ul></section>`:''}<div class="project-actions"><button class="button gold" data-record-work="${escape(p.id)}">Record work · upgrade building</button><button class="button" data-develop="${escape(p.id)}">Develop with agents ↗</button><button class="button" data-add-development="${escape(p.id)}">＋ Add development</button><button class="button" data-back-zone="${p.zone}">District overview</button></div>${related.length?`<h3 class="connections-heading">Connected ideas</h3><div class="project-connections">${related.map(q=>`<button data-project="${escape(q.id)}">${escape(q.name)} ↗</button>`).join('')}</div>`:''}<p class="fine-print"><a href="${import.meta.env.BASE_URL}assets/projects/${assetName(p)}.glb" download>Download this building · GLB ↗</a></p><div class="panel-divider"></div><div class="eyebrow">THE IDEA'S EVOLUTION</div>${p.events.slice().reverse().map(eventCard).join('')}`;$('district-panel').hidden=false;document.body.classList.add('inspecting');}
const thumbnails=new Map<string,string>();
function toast(message:string){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function persist(){try{localStorage.setItem('karmic-public-world-v1',JSON.stringify(save));$('save-status').textContent='● Local backup saved';repository?.save();}catch{toast('Device storage is full or unavailable. Export your world to keep this update.');$('save-status').textContent='○ Export to save';}}
const formatDate=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString('en-IN',{month:'short',day:'numeric',year:'numeric'});
function refreshDates(preferred?:string){dates=[...new Set(save.events.map(e=>e.date))].sort();date=preferred&&dates.includes(preferred)?preferred:dates.at(-1)!;$('date-picker').innerHTML=dates.map(d=>`<option value="${d}" ${date===d?'selected':''}>${formatDate(d)}</option>`).join('');}
let world:ReturnType<typeof createWorld>|undefined;
function render(){const records=worldAt(save,date);const events=save.events.filter(e=>e.date<=date);$('project-count').textContent=String(projectsAt(save,date).length);$('district-count').textContent=String(records.filter(z=>z.level).length);$('event-count').textContent=String(events.length);$('xp-count').textContent=(events.length*20).toLocaleString();$('day-heading').innerHTML=`Day ${dayNumber(date)} <span>· ${formatDate(date)}</span>`;$<HTMLSelectElement>('date-picker').value=date;$<HTMLButtonElement>('prev-day').disabled=date===dates[0];$<HTMLButtonElement>('next-day').disabled=date===dates.at(-1);world?.rebuild(save,date);document.body.classList.toggle('night',save.night);$('toggle-night').textContent=save.night?'☀':'☾';$('stage-date').textContent='Day '+dayNumber(date)+' · '+formatDate(date);calendarMonth=date.slice(0,7);renderCalendar();renderGrowth();if(document.body.classList.contains('archive-open'))renderSnapshots();if(activeProject)showProject(activeProject,false);else if(activeZone)showDistrict(activeZone,false);}
function renderGrowth(){
 const projects=projectsAt(save,date),worked=projects.filter(p=>progression(p.events).sessions>0),work=save.events.filter(e=>e.date<=date&&e.work);
 const picks=['windpanel','webroker','robotics-core'].map(id=>projects.find(p=>p.id===id)).filter((p):p is LivingProject=>!!p);
 $('growth-quests').innerHTML=picks.map(p=>'<button data-record-work="'+escape(p.id)+'"><i>＋</i><span>'+escape(landmarks[p.id]?.name??p.name)+'<small>Record work · Level '+progression(p.events).level+'</small></span></button>').join('');
 $('growth-progress').innerHTML='<strong>'+worked.length+' / '+projects.length+' places evolving</strong>'+work.length+' recorded work entries · '+work.filter(e=>e.actor==='User').length+' by you'+(world?.residentCount?'<span class="resident-summary">'+world.residentCount+' world residents · running, making & playing</span>':'');
 const dots=Object.entries(landmarks).filter(([id])=>projects.some(p=>p.id===id)).map(([id,p])=>'<circle cx="'+(p.x+40)+'" cy="'+(p.z+38)+'" r="1.6"><title>'+escape(landmarks[id].name)+'</title></circle>').join('');
 $('mini-map-content').innerHTML='<svg viewBox="0 0 80 83" aria-label="Map of landmark locations" role="img"><path d="M20 10 L40 5 61 9 72 22 76 47 68 73 43 79 18 72 4 51 7 27 Z" fill="#3c6b55" stroke="#72a697" stroke-width="1.5"/><path d="M44 12 Q50 30 45 47 T43 78 M46 55 L72 55" fill="none" stroke="#57b6c4" stroke-width="2"/>'+dots+'</svg>';
}
function selectSnapshot(d:string){closeDistrict();world?.home();date=d;render();}
function renderCalendar(){const first=new Date(calendarMonth+'-01T00:00:00'),year=first.getFullYear(),month=first.getMonth(),count=new Date(year,month+1,0).getDate(),offset=(first.getDay()+6)%7;$('calendar-month').textContent=first.toLocaleDateString('en-IN',{month:'long',year:'numeric'});$('calendar-days').innerHTML='<span></span>'.repeat(offset)+Array.from({length:count},(_,i)=>{const d=calendarMonth+'-'+String(i+1).padStart(2,'0');return `<button data-day="${d}" class="${d===date?'selected-day':''}" ${dates.includes(d)?'':'disabled'} aria-label="Snapshot ${d}">${i+1}</button>`;}).join('');}
function renderSnapshots(){const shown=[...new Set([date,...dates.slice(-4)])].sort();let rebuilt=false;$('snapshot-strip').innerHTML=shown.map(d=>{const records=worldAt(save,d).filter(z=>z.level),count=save.events.filter(e=>e.date<=d).length,key=d+':'+save.night+':'+projectsAt(save,d).map(p=>p.id+':'+p.plot+':'+progression(p.events).level).join(',')+':'+records.map(z=>z.id+z.level).join(',');let image=thumbnails.get(key);if(!image&&world){image=world.snapshot(save,d);thumbnails.set(key,image);rebuilt=true;if(thumbnails.size>32)thumbnails.delete(thumbnails.keys().next().value!);}return `<button class="snapshot-card ${date===d?'current':''}" data-snapshot="${d}" aria-label="View snapshot ${formatDate(d)}">${image?`<img src="${image}" alt="Island on ${formatDate(d)}">`:'<div class="snapshot-fallback">✦</div>'}<strong>${formatDate(d)}</strong><small>${records.length} districts · ${count} memories</small></button>`;}).join('');if(rebuilt)world?.rebuild(save,date);const strip=$('snapshot-strip'),selected=strip.querySelector<HTMLElement>('.current');if(selected)strip.scrollLeft=Math.max(0,selected.offsetLeft-strip.clientWidth+selected.clientWidth);}
function eventCard(e:LifeEvent){return `<article class="event"><div class="event-meta"><span>${escape(e.kind==='agent'?'Agent idea':e.kind==='build'?'Recorded build':e.kind==='conversation'?'Conversation':'Idea')}</span><time>${formatDate(e.date)}${e.dateEnd?' – '+formatDate(e.dateEnd):''}</time></div><h3>${escape(e.title)}</h3><p>${escape(e.summary)}</p><small>From ${escape(e.sourceTitle)}${e.actor?' · '+escape(e.actor):''}</small><small class="truth-badge">${truthOf(e).replaceAll('_',' ')}</small>${e.work?`<p class="work-evidence"><strong>${escape(e.work.type)} · work recorded</strong><br>${escape(e.work.evidence)}</p>`:''}</article>`;}
function showDistrict(id:ZoneId,visit=true){activeProject=undefined;activeZone=id;const zone=worldAt(save,date).find(z=>z.id===id)!;if(visit&&!save.visited.includes(id)){save.visited.push(id);persist();}world?.focus(id);$('district-content').innerHTML=`<div class="eyebrow">${zone.level?'LEVEL '+zone.level:'UNDISCOVERED'} · ${zone.events.length} MEMORIES</div><span class="district-symbol" style="color:${zone.color}">${({home:'⌂',wind:'✣',knowledge:'▤',spirit:'✺',agents:'◈',ideas:'❋',transit:'⇄',maker:'⚒',mentor:'✧',business:'▥',health:'❀',creative:'✎'})[id]}</span><h2>${zone.name}</h2><p class="description">${zone.description}</p>${id==='agents'?'<div class="notice">Open Agent HQ in the top bar to assign ideas, follow the live conversation, and pause local model work.</div>':''}<div class="panel-divider"></div><div class="eyebrow">INVENTIONS IN THIS DISTRICT</div><div class="district-projects">${projectsAt(save,date).filter(p=>p.zone===id).map(projectTile).join('')}</div><div class="eyebrow">RECENT DEVELOPMENTS</div>${zone.events.length?zone.events.slice().reverse().slice(0,15).map(eventCard).join(''):'<p>No memories here at this point in the timeline.</p>'}`;$('district-panel').hidden=false;document.body.classList.add('inspecting');}
function closeDistrict(){activeProject=undefined;activeZone=undefined;world?.clearFocus();$('district-panel').hidden=true;document.body.classList.remove('inspecting');}
function modal(content:string){swarmDialog=false;$('modal-content').innerHTML=content;$<HTMLDialogElement>('modal').showModal();}
function showJournal(){modal(`<div class="eyebrow">THE WORLD REMEMBERS</div><h2>Your journal</h2><p>Ideas, conversations, and discoveries through ${formatDate(date)}.</p><div class="journal-list">${save.events.filter(e=>e.date<=date).slice().reverse().map(eventCard).join('')}</div>`);}
function showImport(){modal(`<div class="eyebrow">BRING YOUR HISTORY HOME</div><h2>A world made from<br>your conversations.</h2><p>Choose the conversations JSON from your ChatGPT data export, or a previously exported Karmic world.</p><div class="notice">PUBLIC REPOSITORY: imported text, source references, and contributions sync to public GitHub. Only import material you intend to publish. Each dated user message becomes a memory; district suggestions use the conversation title. Images and attachments are not imported. You can revisit the original chats to refine these memories later.</div><button id="choose-file" class="button gold wide">Choose JSON file ↥</button><p class="fine-print">Importing the same messages again updates them without adding duplicates. Current world memories are kept.</p>`);$('choose-file').onclick=()=>$('file-input').click();}
function showIdea(projectId=''){const existing=projectsAt(save,'9999-12-31');modal(`<div class="eyebrow">MAKE ROOM FOR A NEW POSSIBILITY</div><h2>Plant an idea.</h2><div class="notice">PUBLIC WORLD: this idea and its details will be visible on GitHub when synchronized.</div><form id="idea-form"><label>Start or continue a project<select name="project" id="idea-project"><option value="">New invention · create a permanent place</option>${existing.map(p=>`<option value="${escape(p.id)}" ${p.id===projectId?'selected':''}>${escape(p.name)}</option>`).join('')}</select></label><label>Give it a name<input name="title" required maxlength="160" placeholder="What if we could…"></label><label>A little more about it<textarea name="summary" required maxlength="1800" rows="3" placeholder="A thought, a project, a connection worth keeping."></textarea></label><div class="form-row"><label>Its place in the world<select name="zone">${zones.map(z=>`<option value="${z.id}" ${z.id==='ideas'?'selected':''}>${z.name}</option>`).join('')}</select></label><label>Date<input type="date" name="date" required value="${new Date(Date.now()+19800000).toISOString().slice(0,10)}"></label></div><button class="button gold wide" type="submit">Add to my world ＋</button></form>`);const projectChoice=$<HTMLSelectElement>('idea-project'),zoneChoice=document.querySelector<HTMLSelectElement>('#idea-form [name=zone]')!;function syncProjectZone(){const p=existing.find(p=>p.id===projectChoice.value);zoneChoice.disabled=!!p;if(p)zoneChoice.value=p.zone;}projectChoice.onchange=syncProjectZone;syncProjectZone();$('idea-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const project=existing.find(p=>p.id===f.get('project'));const event=validateEvent({...(project?{project}:{}),id:'idea:'+crypto.randomUUID(),title:String(f.get('title')).trim(),summary:String(f.get('summary')).trim(),date:f.get('date'),zone:project?.zone??f.get('zone'),kind:'idea',actor:'User',truthState:'USER_IDEA',sourceTitle:'Your world journal'});save.events=mergeEvents(save.events,[event]);persist();refreshDates(event.date);render();$<HTMLDialogElement>('modal').close();const added=save.events.find(e=>e.id===event.id)!;showProject(added.project!.id);toast(project?'Your idea has a new development.':'A new invention has a permanent home.');}catch(error){toast((error as Error).message);}};}
$('explore').onclick=()=>modal(`<div class="eyebrow">TWELVE PLACES TO GET LOST IN</div><h2>Your island atlas</h2><p>Select a district to discover its story.</p><div class="atlas">${worldAt(save,date).map(z=>`<button data-zone="${z.id}" class="atlas-item"><span style="background:${z.color}"></span><strong>${z.name}</strong><small>${z.events.length} memories · ${z.level?'Level '+z.level:'Not yet discovered'}</small></button>`).join('')}</div>`);
$('modal-content').addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-zone]');if(button){$<HTMLDialogElement>('modal').close();showDistrict(button.dataset.zone as ZoneId);}});
$('close-modal').onclick=()=>$<HTMLDialogElement>('modal').close();$('close-district').onclick=closeDistrict;
$('open-idea').onclick=()=>showIdea();$('open-import').onclick=showImport;$('open-journal').onclick=showJournal;
$('reset-camera').onclick=()=>{world?.home();closeDistrict();};$('zoom-in').onclick=()=>world?.zoom(.8);$('zoom-out').onclick=()=>world?.zoom(1.25);$('toggle-labels').onclick=()=>world?.toggleLabels();
$('toggle-night').onclick=()=>{save.night=!save.night;persist();world?.setNight(save.night);document.body.classList.toggle('night',save.night);$('toggle-night').textContent=save.night?'☀':'☾';};
$('date-picker').onchange=e=>selectSnapshot((e.target as HTMLSelectElement).value);$('prev-day').onclick=()=>selectSnapshot(dates[Math.max(0,dates.indexOf(date)-1)]);$('next-day').onclick=()=>selectSnapshot(dates[Math.min(dates.length-1,dates.indexOf(date)+1)]);
$('open-coverage').onclick=()=>modal(`<div class="eyebrow">WHERE YOUR WORLD COMES FROM</div><h2>Your conversations.<br>Your growing world.</h2><p>This public world contains ${inventionProjects.length} invention places from the public visual catalogue, released on 22 September 2026. The release date is a catalogue snapshot, not a reconstruction of personal history. No private conversations or personal records are included.</p><div class="notice">PUBLIC WORLD: new ideas, imports, work records, and agent contributions are synchronized to public GitHub. Fantasy XP rewards world memories: 20 per event. Building levels reflect recorded research, design, prototypes, tests, and shipped work; idea mentions alone do not add floors. These are game mechanics, not measurements of real-world achievement.</div><p>Local agents can develop assigned ideas together. Automatic daily history collection is not connected yet. Repeated imported messages are deduplicated.</p><button class="button gold wide" id="coverage-import">Import more history</button>`);
$('modal-content').addEventListener('click',e=>{if((e.target as HTMLElement).id==='coverage-import'){ $<HTMLDialogElement>('modal').close();showImport();}});
$<HTMLInputElement>('file-input').onchange=async e=>{const input=e.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{if(file.size>100*1024*1024)throw new Error('Choose a JSON file smaller than 100 MB.');const incoming=importData(JSON.parse(await file.text()));const before=save.events.length;save.events=mergeEvents(save.events,incoming);persist();refreshDates();render();$<HTMLDialogElement>('modal').close();toast(`${save.events.length-before} new memories imported. Saved locally and queued for PUBLIC repository sync.`);}catch(error){toast('Import failed: '+(error as Error).message);}finally{input.value='';}};
$('export-save').onclick=()=>{const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='karmic-world-'+date+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your world export is ready.');};
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeDistrict();});$('world').addEventListener('world-error',e=>toast((e as CustomEvent).detail));
$('world').addEventListener('world-project-assets-ready',()=>{thumbnails.clear();render();});
$('world').addEventListener('world-assets-ready',e=>{thumbnails.clear();render();if((e as CustomEvent).detail.failed)toast('Some scenery could not load. The island is using its built-in models for those pieces.');});
document.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-day],[data-snapshot],[data-browse-zone]');if(!el)return;const d=el.dataset.day??el.dataset.snapshot;if(d&&dates.includes(d)){selectSnapshot(d);if($<HTMLDialogElement>('modal').open)$<HTMLDialogElement>('modal').close();}if(el.dataset.browseZone)showDistrict(el.dataset.browseZone as ZoneId);});
for(const [id,step]of [['calendar-prev',-1],['calendar-next',1]] as const)$(id).onclick=()=>{const m=new Date(calendarMonth+'-01T12:00:00');m.setMonth(m.getMonth()+step);calendarMonth=m.getFullYear()+'-'+String(m.getMonth()+1).padStart(2,'0');renderCalendar();};
$('nav-world').onclick=()=>{document.body.classList.remove('archive-open');$('nav-world').classList.add('rail-active');$('nav-archive').classList.remove('rail-active');closeDistrict();world?.home();};
$('nav-archive').onclick=()=>{const open=document.body.classList.toggle('archive-open');$('nav-archive').classList.toggle('rail-active',open);$('nav-world').classList.toggle('rail-active',!open);closeDistrict();if(open)renderSnapshots();};
$('archive-import').onclick=showImport;
$('map-overview').onclick=()=>{closeDistrict();world?.archipelago();};
$('nav-calendar').onclick=()=>modal(`<div class="eyebrow">YOUR WORLD THROUGH TIME</div><h2>Snapshot calendar</h2><p>Choose a saved date to revisit the island as it was.</p><div class="atlas">${dates.map(d=>`<button class="atlas-item" data-day="${d}"><strong>${formatDate(d)}</strong><small>${save.events.filter(e=>e.date<=d).length} memories</small></button>`).join('')}</div>`);
$('nav-ideas').onclick=showProjects;$('nav-about').onclick=()=>$('open-coverage').click();$('nav-agents').onclick=$('activity-open').onclick=()=>showSwarm();
refreshDates();
try{world=createWorld($('world'),showDistrict,showProject);}catch{const fallback=document.createElement('div');fallback.className='graphics-fallback';fallback.innerHTML='<h2>Your island needs WebGL.</h2><p>Enable hardware acceleration or try another browser. Your journal, import, and save features still work.</p>';$('world').replaceChildren(fallback);}
render();
const effectsButton=document.createElement('button');effectsButton.textContent='✧';effectsButton.title='Toggle cinematic effects';effectsButton.setAttribute('aria-label','Toggle cinematic effects');effectsButton.setAttribute('aria-pressed','true');effectsButton.onclick=()=>{const on=world?.toggleEffects()??false;effectsButton.setAttribute('aria-pressed',String(on));thumbnails.clear();render();toast(on?'Cinematic effects on':'Lightweight rendering on');};document.querySelector('.side-tools')!.append(effectsButton);
const swarmButton=document.createElement('button');swarmButton.id='open-swarm';swarmButton.className='button subtle swarm-button';swarmButton.textContent='◉ Agent HQ';document.querySelector('.top-actions')!.prepend(swarmButton);
function swarmContent(){return `<div class="agent-roster">${swarm?.agents.map(a=>`<article><i style="background:${a.color}"></i><div><strong>${escape(a.name)} <small>${escape(a.role)}</small></strong><p>${escape(a.status==='thinking'?'Developing an idea…':a.status==='completed'?'Contribution ready':'Ready for a task')}</p></div><span class="agent-status ${a.status}">${escape(a.status)}</span></article>`).join('')??'<p>The local agent server is offline. Run the local development server to connect.</p>'}</div>${swarm?.lastError?`<div class="notice">${escape(swarm.lastError)}</div>`:''}<div class="agent-chat">${swarm?.history.slice(-9).reverse().map(r=>`<article class="event"><div class="event-meta"><span>${escape(r.agent)} · ${escape(r.role)}</span><time>${new Date(r.date).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time></div><h3>${escape(r.title)}</h3><p>${escape(r.text)}</p><small>Local model contribution · saved to the world journal</small></article>`).join('')||'<p class="description">Assign an idea to begin. Nova explores it, Sage challenges it, and Pixel proposes the next build. Their actual responses appear here and become memories in the world.</p>'}</div>`;}
function showSwarm(projectId=''){const projects=projectsAt(save,date);modal(`<div class="eyebrow">LITTLE CHARACTERS. REAL CONTRIBUTIONS.</div><h2>Your idea companions.</h2><div class="notice">PUBLIC WORLD: agent reports are saved as public repository contributions.</div><p>Three agents share context and work on one idea together, using the AI model already on your laptop.</p><div class="assignment"><label>Choose an idea<select id="agent-idea">${projects.map(p=>`<option value="${escape(p.id)}" ${p.id===projectId?'selected':''}>${escape(p.name)}</option>`).join('')}</select></label><div class="agent-actions"><button id="assign-agent" class="button gold" ${swarm?.active?'disabled':''}>Develop this idea ↗</button><button id="pause-agents" class="button subtle" ${swarm?.active?'':'disabled'}>Pause</button></div></div><div id="live-agents">${swarmContent()}</div><p class="fine-print">These agents propose and critique ideas. They cannot browse, edit files, or perform experiments. Each assignment ends after three contributions. The local server and laptop must stay running.</p>`);swarmDialog=true;$('assign-agent').onclick=async()=>{const e=projects.find(p=>p.id===$<HTMLSelectElement>('agent-idea').value);if(!e)return;try{$<HTMLButtonElement>('assign-agent').disabled=true;await assignIdea({title:e.name,summary:projectContext(e),zone:e.zone,projectId:e.id});toast('Assignment sent. The companions are getting to work.');}catch(error){toast((error as Error).message);$<HTMLButtonElement>('assign-agent').disabled=false;}};$('pause-agents').onclick=async()=>{await pauseSwarm();toast('Pausing the current assignment. Finished contributions are kept.');};}
swarmButton.onclick=()=>showSwarm();
watchSwarm(s=>{
 swarm=s;world?.setAgents(s.agents);swarmButton.textContent=s.active?'◉ Agents working':'◉ Agent HQ';swarmButton.classList.toggle('agents-working',s.active);
 $('agent-live-state').textContent=s.active?'WORKING':'CONNECTED';$('activity-feed').innerHTML=s.agents.map(a=>`<div class="activity-person"><i style="background:${a.color}"></i><div><strong>${escape(a.name)}</strong><small>${escape(a.role)}</small></div><span>${escape(a.status)}</span></div>`).join('')+(s.history.length?`<p class="activity-excerpt"><strong>Latest · ${escape(s.history.at(-1)!.agent)}</strong><br>${escape(s.history.at(-1)!.text.slice(0,125))}…</p>`:'<p class="activity-excerpt">Choose an idea at Agent HQ to start a conversation.</p>');
 const fresh=s.history.filter(r=>!save.events.some(e=>e.id==='agent:'+r.id));if(fresh.length){const incoming:LifeEvent[]=fresh.map(r=>({id:'agent:'+r.id,date:new Date(Date.parse(r.date)+19800000).toISOString().slice(0,10),title:r.title+' · '+r.role,summary:r.text,zone:r.zone,kind:'agent',actor:r.agent,truthState:'AGENT_HYPOTHESIS',sourceTitle:r.agent+' / local AI',...(save.events.find(e=>e.project?.id===r.projectId)?.project?{project:save.events.find(e=>e.project?.id===r.projectId)!.project}:{})}));save.events=mergeEvents(save.events,incoming);persist();refreshDates();render();}
 const signature=JSON.stringify([s.phase,s.agents.map(a=>a.status),s.history.length,s.lastError]);if(signature!==lastSwarmSignature&&swarmDialog&&$<HTMLDialogElement>('modal').open&&$('live-agents')){$('live-agents').innerHTML=swarmContent();$<HTMLButtonElement>('assign-agent').disabled=s.active;$<HTMLButtonElement>('pause-agents').disabled=!s.active;}lastSwarmSignature=signature;
},()=>{swarmButton.textContent='○ Agent HQ';$('agent-live-state').textContent='OFFLINE';$('activity-feed').innerHTML='<p class="activity-excerpt">Start the local server to connect your idea companions. Your saved world is still here.</p>';});

const libraryButton=document.createElement('button');libraryButton.className='button subtle library-button';libraryButton.textContent='✦ Ideas';libraryButton.id='open-projects';libraryButton.onclick=showProjects;document.querySelector('.top-actions')!.prepend(libraryButton);
document.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-project],[data-develop],[data-add-development],[data-back-zone],[data-record-work]');if(!b)return;if(b.dataset.project){$<HTMLDialogElement>('modal').close();showProject(b.dataset.project);}else if(b.dataset.recordWork)showWork(b.dataset.recordWork);else if(b.dataset.develop)showSwarm(b.dataset.develop);else if(b.dataset.addDevelopment)showIdea(b.dataset.addDevelopment);else if(b.dataset.backZone)showDistrict(b.dataset.backZone as ZoneId);});

function showWork(id:string){const project=projectsAt(save,'9999-12-31').find(p=>p.id===id);if(!project)return;modal(`<div class="eyebrow">YOUR WORK CHANGES THE WORLD</div><h2>Grow ${escape(project.name)}.</h2><div class="notice">PUBLIC WORLD: work records and evidence references will be visible on GitHub when synchronized. Use public references only.</div><form id="work-form"><label>What did you work on?<input name="title" required maxlength="160" placeholder="Designed the test rig"></label><label>What changed?<textarea name="summary" required maxlength="1800" rows="3" placeholder="The work you did and what you learned."></textarea></label><div class="form-row"><label>Work stage<select name="type">${workTypes.map(t=>`<option value="${t}">${t[0].toUpperCase()+t.slice(1)}</option>`).join('')}</select></label><label>Date<input name="date" type="date" required value="${new Date(Date.now()+19800000).toISOString().slice(0,10)}"></label></div><label>Record or reference<input name="evidence" required maxlength="1000" placeholder="Notes, a file, commit, photo reference, or your work record"></label><button class="button gold wide" type="submit">Save work & upgrade building</button><p class="fine-print">Saved as your reported work, with its reference and date. Agent contributions keep their own attribution.</p></form>`);$('work-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const event=validateEvent({id:'work:'+crypto.randomUUID(),date:String(f.get('date')),title:String(f.get('title')).trim(),summary:String(f.get('summary')).trim(),zone:project.zone,project,kind:'build',actor:'User',truthState:'VERIFIED_REALITY',sourceTitle:'Your reported work',work:{type:f.get('type') as WorkType,evidence:String(f.get('evidence')).trim()}});save.events=mergeEvents(save.events,[event]);persist();thumbnails.clear();refreshDates(event.date);render();$<HTMLDialogElement>('modal').close();showProject(id);toast('Work recorded. Your building has grown.');}catch(error){toast((error as Error).message);}};}
const mapButton=document.createElement('button');mapButton.textContent='◎';mapButton.setAttribute('aria-label','View the whole civilization');mapButton.title='View the whole civilization';mapButton.onclick=()=>{closeDistrict();world?.archipelago();};document.querySelector('.side-tools')!.prepend(mapButton);
const syncButton=document.createElement('button');syncButton.className='button subtle sync-button';syncButton.id='repo-sync';syncButton.textContent='↻ Connecting';syncButton.onclick=()=>{modal(`<div class="eyebrow">ONE SHARED WORLD</div><h2>GitHub sync</h2><p>${escape(repoStatus.message)}</p><p>Your world lives in the PUBLIC <strong>karmic-life-game-</strong> repository. Agents record contributions with their names, source references, and truth states.</p><div class="notice">The desktop sync worker checks every minute while this computer is awake and connected. Conflicting edits pause sync for review. Uncommitted code stays with its author until they commit it.</div><p class="fine-print">${repoStatus.lastSyncedAt?'Last synced: '+escape(new Date(repoStatus.lastSyncedAt).toLocaleString()):'No successful sync recorded yet.'}${repoStatus.commit?' · '+escape(repoStatus.commit.slice(0,8)):''}</p><button id="sync-now" class="button gold wide">Sync now ↻</button>`);$('sync-now').onclick=()=>{void repository?.sync();toast('Sync requested. Local contributions are safe in the repository.');};};document.querySelector('.top-actions')!.prepend(syncButton);
repository=connectRepository(()=>save.events,events=>{const combined=mergeEvents(save.events,events);if(JSON.stringify(combined)===JSON.stringify(save.events))return;save.events=combined;try{localStorage.setItem('karmic-public-world-v1',JSON.stringify(save));}catch{}thumbnails.clear();refreshDates(date);render();},status=>{repoStatus=status;syncButton.textContent=({synced:'✓ GitHub synced',syncing:'↻ Syncing',pending:'↻ Saved · sync queued',paused:'◷ Sync paused',conflict:'! Review sync',offline:'○ Local backup',waiting:'◷ Launch to sync'})[status.status]??'↻ GitHub';syncButton.title=status.message;syncButton.dataset.status=status.status;});
